import type { Conversation } from './types'

export const conversationsMock: Conversation[] = [
  {
    id: 1,
    participant: {
      id: 'carlos-mendes',
      name: 'Carlos Mendes',
      avatarUrl: '/images/picture_carlos_mendes.png',
    },
    unreadCount: 7,
    isArchived: false,
    isParticipantTyping: true,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 1,
        senderId: 'me',
        senderName: 'Roberto Silva',
        senderType: 'me',
        content: 'Olá Carlos, tudo bem com você?',
        createdAt: '2026-03-01T13:45:00',
        visualized: true,
      },
      {
        id: 2,
        conversationId: 1,
        senderId: 'carlos-mendes',
        senderName: 'Carlos',
        senderType: 'participant',
        content: 'Bom dia Roberto, por aqui tudo certo! E com você?',
        createdAt: '2026-03-01T13:56:00',
        visualized: false,
      },
      {
        id: 3,
        conversationId: 1,
        senderId: 'carlos-mendes',
        senderName: 'Carlos',
        senderType: 'participant',
        content: 'Você conseguiu validar o documento?',
        createdAt: '2026-03-01T14:50:00',
        visualized: false,
      },
    ],
  },
  {
    id: 2,
    participant: {
      id: 'luiz-ferreira',
      name: 'Luiz Ferreira',
      avatarUrl: '/images/picture_luiz_ferreira.jpg',
    },
    unreadCount: 7,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 2,
        senderId: 'luiz-ferreira',
        senderName: 'Luiz',
        senderType: 'participant',
        content: 'Concordo com a proposta enviada.',
        createdAt: '2026-03-01T14:45:00',
        visualized: false,
      },
    ],
  },
  {
    id: 3,
    participant: {
      id: 'maria-silva',
      name: 'Maria Silva',
      avatarUrl: '/images/picture_maria_silva.jpg',
    },
    unreadCount: 5,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 3,
        senderId: 'maria-silva',
        senderName: 'Maria',
        senderType: 'participant',
        content: 'Claro! Estou disponível para conversar ainda hoje.',
        createdAt: '2026-03-01T13:10:00',
        visualized: false,
      },
    ],
  },
  {
    id: 4,
    participant: {
      id: 'ana-costa',
      name: 'Ana Costa',
      avatarUrl: '/images/picture_ana_costa.jpg',
    },
    unreadCount: 9,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 4,
        senderId: 'ana-costa',
        senderName: 'Ana',
        senderType: 'participant',
        content:
          'A reunião foi muito produtiva hoje. Consegui alinhar os próximos passos com a equipe.',
        createdAt: '2026-03-01T15:20:00',
        visualized: false,
      },
    ],
  },
  {
    id: 5,
    participant: {
      id: 'joao-pereira',
      name: 'João Pereira',
      avatarUrl: '/images/picture_joao_pereira.jpg',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 5,
        senderId: 'joao-pereira',
        senderName: 'João',
        senderType: 'participant',
        content: 'Podemos rever o cronograma na próxima chamada.',
        createdAt: '2026-03-01T16:05:00',
        visualized: true,
      },
    ],
  },
  {
    id: 6,
    participant: {
      id: 'fernanda-alves',
      name: 'Fernanda Alves',
      avatarUrl: '/images/picture_fernanda_alves.jpg',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 6,
        senderId: 'fernanda-alves',
        senderName: 'Fernanda',
        senderType: 'participant',
        content: 'Estou ansiosa para os resultados. Assim que tiver uma atualização, me avisa?',
        createdAt: '2026-03-01T16:45:00',
        visualized: true,
      },
    ],
  },
  {
    id: 7,
    participant: {
      id: 'ricardo-lima',
      name: 'Ricardo Lima',
      avatarUrl: '/images/picture_ricardo_lima.jpg',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 7,
        senderId: 'ricardo-lima',
        senderName: 'Ricardo',
        senderType: 'participant',
        content:
          'Precisamos de mais dados antes de decidir. Vou levantar as informações com o time.',
        createdAt: '2025-08-23T10:30:00',
        visualized: true,
      },
    ],
  },
  {
    id: 8,
    participant: {
      id: 'beatriz-souza',
      name: 'Beatriz Souza',
      avatarUrl: '/images/picture_beatriz_souza.jpg',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 8,
        senderId: 'beatriz-souza',
        senderName: 'Beatriz',
        senderType: 'participant',
        content: 'Você tem o contato do jurídico?',
        createdAt: '2025-08-24T09:12:00',
        visualized: true,
      },
      {
        id: 2,
        conversationId: 8,
        senderId: 'me',
        senderName: 'Roberto Silva',
        senderType: 'me',
        content: 'Claro! É o juridico@empresa.com.br',
        createdAt: '2025-08-24T09:18:00',
        visualized: true,
      },
    ],
  },

  {
    id: 9,
    participant: {
      id: 'patricia-gomes',
      name: 'Patrícia Gomes',
      avatarUrl: '/images/picture_maria_silva.jpg',
    },
    unreadCount: 3,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 9,
        senderId: 'patricia-gomes',
        senderName: 'Patrícia',
        senderType: 'participant',
        content: 'Enviei o documento revisado para aprovação.',
        createdAt: '2026-03-01T17:10:00',
        visualized: false,
      },
    ],
  },
  {
    id: 10,
    participant: {
      id: 'marcos-vinicius',
      name: 'Marcos Vinícius',
      avatarUrl: '/images/picture_ricardo_lima.jpg',
    },
    unreadCount: 1,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 10,
        senderId: 'marcos-vinicius',
        senderName: 'Marcos',
        senderType: 'participant',
        content: 'Ajustei os pontos que você comentou ontem.',
        createdAt: '2026-03-01T17:35:00',
        visualized: false,
      },
    ],
  },
  {
    id: 11,
    participant: {
      id: 'juliana-rocha',
      name: 'Juliana Rocha',
      avatarUrl: '/images/picture_maria_silva.jpg',
    },
    unreadCount: 4,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 11,
        senderId: 'juliana-rocha',
        senderName: 'Juliana',
        senderType: 'participant',
        content: 'Podemos alinhar isso ainda hoje?',
        createdAt: '2026-03-01T18:05:00',
        visualized: false,
      },
    ],
  },
  {
    id: 12,
    participant: {
      id: 'rafael-martins',
      name: 'Rafael Martins',
      avatarUrl: '/images/picture_carlos_mendes.png',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 12,
        senderId: 'rafael-martins',
        senderName: 'Rafael',
        senderType: 'participant',
        content: 'Ficou pendente apenas a validação final.',
        createdAt: '2026-03-01T18:30:00',
        visualized: true,
      },
    ],
  },
  {
    id: 13,
    participant: {
      id: 'camila-torres',
      name: 'Camila Torres',
      avatarUrl: '/images/picture_ana_costa.jpg',
    },
    unreadCount: 2,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 13,
        senderId: 'camila-torres',
        senderName: 'Camila',
        senderType: 'participant',
        content: 'A equipe já foi avisada sobre a alteração.',
        createdAt: '2026-03-01T19:00:00',
        visualized: false,
      },
    ],
  },
  {
    id: 14,
    participant: {
      id: 'bruno-almeida',
      name: 'Bruno Almeida',
      avatarUrl: '/images/picture_luiz_ferreira.jpg',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 14,
        senderId: 'bruno-almeida',
        senderName: 'Bruno',
        senderType: 'participant',
        content: 'Vou conferir os dados e retorno em seguida.',
        createdAt: '2026-03-01T19:25:00',
        visualized: true,
      },
    ],
  },
  {
    id: 15,
    participant: {
      id: 'larissa-nunes',
      name: 'Larissa Nunes',
      avatarUrl: '/images/picture_fernanda_alves.jpg',
    },
    unreadCount: 6,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 15,
        senderId: 'larissa-nunes',
        senderName: 'Larissa',
        senderType: 'participant',
        content: 'A apresentação ficou ótima, só ajustei o título.',
        createdAt: '2026-03-01T20:15:00',
        visualized: false,
      },
    ],
  },
  {
    id: 16,
    participant: {
      id: 'felipe-andrade',
      name: 'Felipe Andrade',
      avatarUrl: '/images/picture_ricardo_lima.jpg',
    },
    unreadCount: 0,
    isArchived: false,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 16,
        senderId: 'felipe-andrade',
        senderName: 'Felipe',
        senderType: 'participant',
        content: 'Perfeito, vou seguir com essa versão.',
        createdAt: '2026-03-01T21:10:00',
        visualized: true,
      },
    ],
  },

  // Arquivadas
  {
    id: 17,
    participant: {
      id: 'natalia-ribeiro',
      name: 'Natália Ribeiro',
      avatarUrl: '/images/picture_beatriz_souza.jpg',
    },
    unreadCount: 0,
    isArchived: true,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 17,
        senderId: 'natalia-ribeiro',
        senderName: 'Natália',
        senderType: 'participant',
        content: 'Precisamos atualizar o responsável da tarefa.',
        createdAt: '2026-02-28T14:05:00',
        visualized: true,
      },
    ],
  },
  {
    id: 18,
    participant: {
      id: 'eduardo-lopes',
      name: 'Eduardo Lopes',
      avatarUrl: '/images/picture_joao_pereira.jpg',
    },
    unreadCount: 0,
    isArchived: true,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 18,
        senderId: 'eduardo-lopes',
        senderName: 'Eduardo',
        senderType: 'participant',
        content: 'Recebi a solicitação e já encaminhei ao setor.',
        createdAt: '2026-02-28T15:10:00',
        visualized: true,
      },
    ],
  },
  {
    id: 19,
    participant: {
      id: 'amanda-freitas',
      name: 'Amanda Freitas',
      avatarUrl: '/images/picture_ana_costa.jpg',
    },
    unreadCount: 0,
    isArchived: true,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 19,
        senderId: 'amanda-freitas',
        senderName: 'Amanda',
        senderType: 'participant',
        content: 'A ata da reunião já está disponível.',
        createdAt: '2026-02-28T16:32:00',
        visualized: true,
      },
    ],
  },
  {
    id: 20,
    participant: {
      id: 'gustavo-henrique',
      name: 'Gustavo Henrique',
      avatarUrl: '/images/picture_luiz_ferreira.jpg',
    },
    unreadCount: 0,
    isArchived: true,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 20,
        senderId: 'gustavo-henrique',
        senderName: 'Gustavo',
        senderType: 'participant',
        content: 'Podemos deixar essa pauta para amanhã.',
        createdAt: '2026-02-28T17:45:00',
        visualized: true,
      },
    ],
  },
  {
    id: 21,
    participant: {
      id: 'patricia-gomes-arquivada',
      name: 'Patrícia Gomes',
      avatarUrl: '/images/picture_maria_silva.jpg',
    },
    unreadCount: 0,
    isArchived: true,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 21,
        senderId: 'patricia-gomes',
        senderName: 'Patrícia',
        senderType: 'participant',
        content: 'Podemos retomar esse assunto na próxima semana.',
        createdAt: '2026-02-27T11:30:00',
        visualized: true,
      },
    ],
  },
  {
    id: 22,
    participant: {
      id: 'luiz-ferreira-arquivado',
      name: 'Luiz Ferreira',
      avatarUrl: '/images/picture_luiz_ferreira.jpg',
    },
    unreadCount: 0,
    isArchived: true,
    isParticipantTyping: false,
    newMessagesMarkerExpiresAt: null,
    messages: [
      {
        id: 1,
        conversationId: 22,
        senderId: 'luiz-ferreira',
        senderName: 'Luiz',
        senderType: 'participant',
        content: 'Encerramos essa solicitação por aqui.',
        createdAt: '2026-02-27T10:15:00',
        visualized: true,
      },
    ],
  },
]
